### ISSUE TITLE
error loop

### ISSUE THREAD

**Issue by paulens12** [CM2Walki/TF2#10]
I'm using this command to run the server:
`docker run -d --net=host --name=tf2 -e SRCDS_TOKEN={***} -v /srv/c7c67d06-a5c3-4586-be6a-af277ae13aa2/tf2/tf-dedicated:/home/steam/tf-dedicated -e SRCDS_PORT=26015 -e SRCDS_TV_PORT=26020 -e SRCDS_HOSTNAME="{***}" -e SRCDS_RCONPW="{***}" -e SRCDS_PW="{***}" --memory=8g cm2network/tf2`

I tried both with and without the `--memory` option. Either way, I get through the download and then get stuck in an error loop. Example output:
```
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (48 of 53196 KB)...
[  0%] Downloading update (1998 of 53196 KB)...
[  3%] Downloading update (4222 of 53196 KB)...
[  7%] Downloading update (6158 of 53196 KB)...
[ 11%] Downloading update (7662 of 53196 KB)...
[ 14%] Downloading update (8994 of 53196 KB)...
[ 16%] Downloading update (10330 of 53196 KB)...
[ 19%] Downloading update (11611 of 53196 KB)...
[ 21%] Downloading update (13027 of 53196 KB)...
[ 24%] Downloading update (14343 of 53196 KB)...
[ 26%] Downloading update (15669 of 53196 KB)...
[ 29%] Downloading update (16997 of 53196 KB)...
[ 31%] Downloading update (18524 of 53196 KB)...
[ 34%] Downloading update (19879 of 53196 KB)...
[ 37%] Downloading update (21177 of 53196 KB)...
[ 39%] Downloading update (22504 of 53196 KB)...
[ 42%] Downloading update (23917 of 53196 KB)...
[ 44%] Downloading update (25242 of 53196 KB)...
[ 47%] Downloading update (26567 of 53196 KB)...
[ 49%] Downloading update (27913 of 53196 KB)...
[ 52%] Downloading update (29491 of 53196 KB)...
[ 55%] Downloading update (30846 of 53196 KB)...
[ 57%] Downloading update (32198 of 53196 KB)...
[ 60%] Downloading update (33713 of 53196 KB)...
[ 63%] Downloading update (34369 of 53196 KB)...
[ 64%] Downloading update (35020 of 53196 KB)...
[ 65%] Downloading update (35670 of 53196 KB)...
[ 67%] Downloading update (36409 of 53196 KB)...
[ 68%] Downloading update (37067 of 53196 KB)...
[ 69%] Downloading update (37741 of 53196 KB)...
[ 70%] Downloading update (38440 of 53196 KB)...
[ 72%] Downloading update (39113 of 53196 KB)...
[ 73%] Downloading update (39792 of 53196 KB)...
[ 74%] Downloading update (40561 of 53196 KB)...
[ 76%] Downloading update (41244 of 53196 KB)...
[ 77%] Downloading update (41923 of 53196 KB)...
[ 78%] Downloading update (42602 of 53196 KB)...
[ 80%] Downloading update (43309 of 53196 KB)...
[ 81%] Downloading update (43976 of 53196 KB)...
[ 82%] Downloading update (44644 of 53196 KB)...
[ 83%] Downloading update (45385 of 53196 KB)...
[ 85%] Downloading update (46041 of 53196 KB)...
[ 86%] Downloading update (46686 of 53196 KB)...
[ 87%] Downloading update (47337 of 53196 KB)...
[ 88%] Downloading update (48035 of 53196 KB)...
[ 90%] Downloading update (48685 of 53196 KB)...
[ 91%] Downloading update (49335 of 53196 KB)...
[ 92%] Downloading update (50078 of 53196 KB)...
[ 94%] Downloading update (50724 of 53196 KB)...
[ 95%] Downloading update (51379 of 53196 KB)...
[ 96%] Downloading update (52072 of 53196 KB)...
[ 97%] Downloading update (52743 of 53196 KB)...
[ 99%] Downloading update (53196 of 53196 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
/tmp/dumps insufficient permissions - delete and recreate
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
Success! App '232250' already up to date.
Auto detecting CPU
Using default binary: ./srcds_linux
Server will auto-restart if there is a crash.
Updating server using Steam.
----------------------------
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
@ShutdownOnFailedCommand 1
"@ShutdownOnFailedCommand" = "1"
@NoPromptForPassword 1
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
force_install_dir /home/steam/tf-dedicated
app_update 232250
Success! App '232250' already up to date.
quit
----------------------------
Setting breakpad minidump AppID = 232250
Using breakpad crash handler
Add "-debug" to the /home/steam/tf-dedicated/srcds_run command line to generate a debug.log to help with solving this problem
Sat Jun  5 16:26:45 UTC 2021: Server restart in 10 seconds
```
And then the following section repeats indefinitely:
```
Updating server using Steam.
----------------------------
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
@ShutdownOnFailedCommand 1
"@ShutdownOnFailedCommand" = "1"
@NoPromptForPassword 1
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
force_install_dir /home/steam/tf-dedicated
app_update 232250
Success! App '232250' already up to date.
quit
----------------------------
Setting breakpad minidump AppID = 232250
Using breakpad crash handler
Add "-debug" to the /home/steam/tf-dedicated/srcds_run command line to generate a debug.log to help with solving this problem
Sat Jun  5 16:27:02 UTC 2021: Server restart in 10 seconds
```
I tried editing `entry.sh` to include the `-debug` argument and restarting the container, but that didn't change the output at all.

Then I tried exec'ing into the running container and copy/pasting the last command from `entry.sh` into the shell - I got "Out of memory or address space", but that might be because the `entry.sh` script was still running in this perpetual crash loop...

**Comment by CM2Walki** [comment]
I tried to replicate this yesterday, everything was working as expected.

Would you mind posting (or DMing) the values of:

```
-e SRCDS_HOSTNAME="{***}" -e SRCDS_RCONPW="{***}" -e SRCDS_PW="{***}"
```

Maybe the ones you picked cause srcds (or my entry.sh) to error out.

**Comment by paulens12** [comment]
Thanks for looking into the issue! I'll have to look up the hostname and password when I get home - I remember they were nothing special, just lowercase letters with no numbers or special characters.
As for the RCON password, I used a randomly generated one: K3m@N^bPhFQdAwdn
(not worried about posting it here, as I can always make a new one)
I'm guessing the @ or ^ might have caused the error? I'll try an alphanumerical password once I get home. Thanks for the idea.
________________________________

**Comment by CM2Walki** [comment]
> I'm guessing the @ or ^ might have caused the error? I'll try an alphanumerical password once I get home. Thanks for the idea.

It could, srcds is a old application after all :p.

**Comment by shaggywolfhound** [comment]
I actually have the same issue however I'm using a docker-compose file, just to make my life a little easier.  Here's my file:

version: "3"
services:
    tf2:
        image: cm2network/tf2:latest
        container_name: tf2
        environment:
          - SRCDS_RCONPW=redacted
          - SRCDS_PW=redacted
          - SRCDS_PORT=27015
          - SRCDS_TV_PORT=27020
          #- SRCDS_NET_PUBLIC_ADDRESS="0"
          - SRCDS_IP="0" (local ip to bind)
          - SRCDS_FPSMAX=300
          - SRCDS_TICKRATE=66
          - SRCDS_MAXPLAYERS=14
          - SRCDS_REGION=3
          - SRCDS_HOSTNAME=Divanti-TF2
          - SRCDS_WORKSHOP_START_MAP=0
          - SRCDS_HOST_WORKSHOP_COLLECTION=0
          - SRCDS_WORKSHOP_AUTHKEY="redacted"
          - SRCDS_TOKEN="redacted"
        volumes:
            - ./data:/home/steam/tf-dedicated/
            - ./logs:/home/steam/Steam/logs
        ports:
            - 27015:27015
            - 27020:27020

        network_mode: host

**Comment by neutronstorm** [comment]
I have the same error. On my machine, it traces back to the steam system erroring out with "Out of memory or address space.  Texture quality setting may be too high.".

Despite what you would think, the problem was actually the disk volume that the machine was using was too big! Apparently, the file system that the /home/steam is on must be smaller than 1TB ( not tested ). I was using an 8 exabyte EFS partition and it didn't like that. Changing to a small local partition fixed the issue for me.

**Comment by CM2Walki** [comment]
> Apparently, the file system that the /home/steam is on must be smaller than 1TB ( not tested )

I run mine on 2-4 TB HDDs and they appear fine (32 GB of ram though).

> I was using an 8 exabyte EFS partition and it didn't like that. Changing to a small local partition fixed the issue for me.

This is interesting. srcds might be trying to allocate memory (for something) in relation to the size of the underlying disk. I doubt the limit to that happening is in the terabytes though, it sounds like something that might happen if you have a quiet large underlying hard drive.

My guess is that the issue comes from available memory vs underlying storage size. If you have a VPS machine then you usually run with less ram, however you could still attach a large block storage to it.

@paulens12, @shaggywolfhound & @neutronstorm sorry to ping you in such an old issue. Would you mind providing details about your hosts? Were they VPS, how much storage was attached when you tried to launch the tf2 server?

**Comment by paulens12** [comment]
@CM2Walki my server is self-hosted and has about 8TB of storage and 16GB of RAM. Seems like I forgot to hit reply and now found the tab open lol

**Comment by neutronstorm** [comment]
> @paulens12, @shaggywolfhound & @neutronstorm sorry to ping you in such an old issue. Would you mind providing details about your hosts? Were they VPS, how much storage was attached when you tried to launch the tf2 server?

Yea, I also forgot to reply. I am using an AWS fargate container. The container has access to 2gb or memory. It normally works fine with that amount. The underlying storage is normally an NFS mounted disk with "unlimited" cloud storage. Shows as 8 exabytes. I can change the memory and CPU allocation to the container as needed.
