### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by d-513** [CM2Walki/TF2#13]
I have to manually restart the container every time valvo pushes an update. When they push the update, players cant play on my server. Anyway to automate that with this image? Thanks

**Comment by CM2Walki** [comment]
Technically the image does come with a script that handles updates when the server is idle:
https://github.com/CM2Walki/TF2/blob/master/buster/Dockerfile#L31-L37

It gets passed to the server here:
https://github.com/CM2Walki/TF2/blob/master/etc/entry.sh#L35

I have verified this on CS:GO servers, but never double-checked on TF2 servers. I kind of thought they would also have the same feature. It should work, all 3 values are set correctly; -autoupdate, -steam_dir & -steamcmd_script 🤔

**Comment by dada513** [comment]
> Technically the image does come with a script that handles updates when the server is idle: https://github.com/CM2Walki/TF2/blob/master/buster/Dockerfile#L31-L37
> 
> It gets passed to the server here: https://github.com/CM2Walki/TF2/blob/master/etc/entry.sh#L35
> 
> I have verified this on CS:GO servers, but never double-checked on TF2 servers. I kind of thought they would also have the same feature. It should work, all 3 values are set correctly; -autoupdate, -steam_dir & -steamcmd_script thinking

That's very odd. I've encountered multiple times valve updating the game and clients not able to join until i restart the container which updates it. For now I have a cronjob for container restarts, but would be nice to be handled automatically without server interruption if  no update is available

**Comment by dada513** [comment]
Now that I think about it, I have some bots on the server (via tf_bot_add). Maybe steam counts this as not being idle thus not updating?

**Comment by CM2Walki** [comment]
In CS:GO, server hibernation kicks in even if there are bots on the server. It might be that TF2 bots work differently, since it's obviously based on a bit of an older source engine.
