### ISSUE TITLE
Impossible to switch channel or update mods

### ISSUE THREAD

**Issue by gentlecolts** [CM2Walki/TF2#16]
The current entry logic is as follows:
if, and only if, there isn't already a server config file, check to determine if metamod/sourcemod should be pulled in

This logic has some major issues:
1) if a user switches varient, for exmaple a user installs vanilla but they decide later that they want sourcemod, the entry script will never check for it
2) the entry script will never check for updates, leaving both metamod and sourcemod variants out of date

As it is, it's possible to work around, as the user can move important files out of cfg, allow the image to re-generate them, then move their files back, however this is a very hacky workflow, and it would be more ideal if the entry point could handle this itself.  As a suggested solution, perhaps move those two ifs outside of the "does config exist" check, always check the current version, and install it if it doesn't match what's on disk.  Additionally, ideally the entry would clean up older versions and clean up if the user has switched variant.

It may also be good to bake the latest version tar files for metamod/sourcemod into the respective image(s), and just do the extraction if necessary in the entrypoint

**Comment by CM2Walki** [comment]
**Regarding 1:**
I agree with the fact that `sourcemod` and `metamod` should be downloaded if their respective directories are missing. This change will be applied in the future to both the TF2 and CSGO images. A week ago, I had someone be confused by exactly this behaviour it seems: https://github.com/CM2Walki/CSGO/issues/68

**Regarding 2:**
As to allowing for updates to `sourcemod` and `metamod` I don't see an elegant way of implementing this without potentially wiping user data. I'd be open to ideas on that one. Like is there a version file present in the `metamod` or `sourcemod`?

**Comment by gentlecolts** [comment]
I was looking at it a little more, it seems metamod and/or sourcemod may be able to update themselves, so that might not be an issue, however what may still be an issue is that there doesn't seem to be an obvious way to elegantly automatically remove them if, for example, someone were to start on the sorcemod variant, and then decide they want to go full vanilla

**Comment by gentlecolts** [comment]
Awesome, thank you for addressing this!
