### ISSUE TITLE
Dev build of sourcemod

### ISSUE THREAD

**Issue by kir68k** [CM2Walki/TF2#27]
Hey, I was just wondering whether it's possible to implement this? Instead of using normal sourcemod releases, ship with the latest dev build. My docker knowledge is limited, so asking here.

**Comment by CM2Walki** [comment]
You can adjust the variables `METAMOD_VERSION` and `SOURCEMOD_VERSION` in the `Dockerfile`:

https://github.com/CM2Walki/TF2/blob/master/bookworm/Dockerfile#L79
https://github.com/CM2Walki/TF2/blob/master/bookworm/Dockerfile#L83

and then rebuild the image yourself. This image only ships the latest stable version of sourcemod and metamod which is version `1.11`.
