### ISSUE TITLE
Issue using mapped folder volume

### ISSUE THREAD

**Issue by TechnologyWIN** [CM2Walki/TF2#4]
I have tried several forms of -v /srv/somedir/:/home/steam/tf-dedicated/ and  I have been unable to launch the container.  Launching with with just the volume command (no mapped folder) or no volume works.   I even tried mapping -v /srv/somedir/:/home/ and it still gives me the error:

bash: entry.sh: No such file or directory

There is something going on with entry.sh being located within the /home/steam/tf-dedicated folder.... would it be possible to have entry.sh copied to the / directory?

**Comment by biltongza** [comment]
I made a PR for this in #5.

**Comment by CM2Walki** [comment]
In regards to #5, @biltongza. What's wrong with just moving the entry.sh outside the volume directory (like @TechnologyWIN suggested)? #5 appears to be a bit over-engineered.

**Comment by biltongza** [comment]
I thought about doing that as I put my head to my pillow to sleep last night :) that would definitely be a better solution.

**Comment by biltongza** [comment]
New PR up at #6

**Comment by CM2Walki** [comment]
Merged #6.
